backend:
  name: github
  repo: /Fziliotti/BlogFziliotti
  branch: gh-pages
  site_domain: https://fziliotti.github.io/BlogFziliotti/
media_folder: "assets/img"
publish_mode: editorial_workflow
collections:
  - name: "post" # Used in routes, e.g. /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
      - {label: "Post Image", name: "image", widget: "image"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Introduction", name: "introduction", widget: "string"}
      - {label: "Twitter text", name: "twitter_text", widget: "string"}
      - {label: "Main Class", name: "main-class", widget: "select", options: ["emp", "dsgn", "js", "dev", "comp", "svg"]}
      - {label: "Color", name: "color", widget: "select", options: [
          { label: "emp", value: "#D6BA32" },
          { label: "dsgn", value: "#0E6BA8" },
          { label: "js", value: "#D6BA32" },
          { label: "dev", value: "#74b9ff" },
          { label: "comp", value: "#e17055" },
          { label: "svg", value: "#a29bfe" },
        ]
        }
      - {label: "Tags", name: "tags", widget: "list", default: [""]}
      - {label: "Category", name: "categories", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

    